version: '3.3'
services:
  portainer:
    container_name: portainer
    ports:
        - '9000:9000'
    restart: always
    volumes:
        - '/var/run/docker.sock:/var/run/docker.sock'
        - 'portainer-data:/data'
    image: portainer/portainer
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"


volumes:
  portainer-data:
