version: "3.2"

services:
  nodered:
    image: elzekool/rpi-nodered
    privileged: true
    restart: always
    ports:
      - "1880:1880"
    network_mode: "host"
    volumes:
      - nodered-data:/root/.node-red
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
  mosquitto:
    image: elzekool/rpi-mosquitto
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mqtt-data:/mqtt/data
      - mqtt-log:/mqtt/log
      - mqtt-config:/mqtt/config
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
  netdata:
    image: netdata/netdata
    restart: always
    ports:
      - 19999:19999
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  nodered-data:
  mqtt-data:
  mqtt-log:
  mqtt-config:
